### ISSUE TITLE
Multiband (RGB) GeoTIFF support?

### ISSUE THREAD

**Issue by pierotofy** [DHI-GRAS/terracotta#125]
Hello :hand:

Just stumbled upon this project and I'm really impressed! I've been thinking about building a project with a similar set of functionalities a few weeks ago, but I'm glad somebody preceded me and I'd rather contribute to this existing effort.

Long story short, my goal is to serve RGB Cloud Optimized GeoTIFFs to a Leaflet map. It seems that Terracotta require all files to be singleband (and then merge them back to RGB via /rgb), so a workaround would be to split the GeoTIFF into it's separate bands and then display them via /rgb.

I was just wondering if there would be interest in adding support for reading multiband GeoTIFFs to avoid the extra work of generating 3 separate files? I'm not really sure of the feasibility given the current architecture, but I could contribute to it if there's interest, in which case any guidance or advice on where to start would be much appreciated  :pray:

**Comment by mrpgraae** [comment]
Hi @pierotofy 

Glad that you like Terracotta and that you think it will be useful to you. We would be very happy to have your contributions.

A core philosophy of Terracotta is that we want to make minimal assumptions about the users data. Terracotta is built around the concept of keys, which are arbitrary and completely defined by the user. An example of some keys could be `[location, date, band]` and one set of values for these keys could be `[europe, 20190118, red]`. Each valid combination of key values, must then map to exactly 1 raster and in order to obey the principle of minimal assumptions, we cannot have 'special' keys.

For example, instead of `band` as the last key, we could just as easily have `date` and then use different dates as the r, g, b, channels in the call to /rgb (although I don't know why you would want that). In this sense `band` is not a special key, so putting in special logic for that key does not really make sense.

On the other hand, we do require that the r, g, b parameters to the /rgb call, can only map to values of the last key. So it would actually be possible to add the option of having the last key refer to a band, in a raster identified by the preceding keys.
You would have to add logic to handle this during ingestion and metadata computation and then add a flag to the metadata db. You would then also have to add special logic to the handlers and the functions that load the raster tiles, for the last-key-is-band case.

I'm not convinced that the convenience of not having to split up bands into files, justify adding all this special logic, so for now I would have to say that we're not interested in adding support for this. But you are of course very welcome to fork Terracotta and add this feature if you want.

**Comment by mrpgraae** [comment]
Here is a simple gist that uses Rasterio to split a multi-band raster into 1 file per band https://gist.github.com/mrpgraae/6074a2fea4e50ae79433b260028d6202

**Comment by pierotofy** [comment]
Thanks for the pointers! I speculated that the choice for single bands must have been the result of a design choice to make minimal assumptions about the input data, but this is good.

I will do some testing in the next few weeks to see if splitting the bands works well enough for my use case.

Thanks again! :+1:
