### ISSUE TITLE
Optimize a directory of rasters

### ISSUE THREAD

**Issue by akshatgit** [DHI-GRAS/terracotta#184]
I have a directory in /data/ containing .jp2 files. I regularly do a rsync to upload new rasters. 
Similar to rsync, I would like to optimise only new rasters, and also while ingesting them to create new DB, I would like to ingest the new optimised rasters to append them to an existing SQLite db.

**Comment by j08lue** [comment]
This question is not really specific to Terracotta, but more a question of how you code up your file ingestion pipeline. Terracotta does not include any logic to scan a directory for new files or so, if that is what you are asking about. So you have to code that up yourself.

Some ideas: You could pipe the output of `rsync` to a list and grep out the file names to get the names of the files that were added/updated each time `rsync` runs.

You could also compare the list of local files to the files in the Terracotta database, so you know which ones were not ingested yet.

Another way is to keep a local log of files that were processed, either in a text file, in `original-filename.done` files, in a database, or whatever, and then diff that against the list of `.jp2` files.

I'll close this here, but please feel free to reopen if there are questions specific to Terracotta.

**Comment by dionhaefner** [comment]
Maybe it would be a good idea though to skip COG that are passed into `optimize-rasters` instead of optimizing them again. Would that help?

Otherwise you can use an external optimizer such as `rio-cogeo` to achieve this. With the terracotta Python API it should be easy enough to check which rasters are already ingested.

**Comment by akshatgit** [comment]
Thanks, @j08lue and @dionhaefner for your help. I have filtered out new files that were synced via `rsync` to optimize only new/updated images. 
Currently, I am serving the using -r option to the entire optimized raster images directory. I have yet to see how I can update the sqllite db if I switch to it. 
Also, I am new to terracotta and we are deploying it on k8s. Maybe it makes sense to have an official docker image.

**Comment by akshatgit** [comment]
I have a fair docker experience, I can help with that if it is in pipeline..

**Comment by dionhaefner** [comment]
> Currently, I am serving the using -r option to the entire optimized raster images directory. I have yet to see how I can update the sqllite db if I switch to it.

I think you should definitely use a real database for any serious deployment. [You can check out our guide for examples on how to do that.](https://terracotta-python.readthedocs.io/en/latest/get-started.html#ingestion)

I think there could be value in supplying a stripped-down, lightweight official Docker image, if you want to write one. Otherwise it pretty much just boils down to

```dockerfile
FROM ubuntu:latest
RUN pip install terracotta
```
