### ISSUE TITLE
Support band math

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/terracotta#20]

**Comment by pierotofy** [comment]
This would be amazing!

**Comment by dionhaefner** [comment]
Basic functionality shouldn't be too hard, the real challenge is figuring out which operations to support, and how to pass them in the API. Happy for any ideas.

**Comment by pierotofy** [comment]
Perhaps a subset of QGIS expressions could be a good list:

```
a + b      a plus b
a - b      a minus b
a * b      a multiplied by b
a / b      a divided by b
a % b      a modulo b (for example, 7 % 2 = 1, or 2 fits into 7 three
           times with remainder 1)
a ^ b      a power b (for example, 2^2=4 or 2^3=8)
a = b      a and b are equal
a > b      a is larger than b
a < b      a is smaller than b
a <> b     a and b are not equal
a != b     a and b are not equal
a <= b     a is less than or equal to b
a >= b     a is larger than or equal to b
+ a        positive sign
- a        negative value of a
a AND b      logical AND 
a OR b        logical OR
```

Then support for common math functions such as `cos`, `sin`, `acos`, `tan`, `sqrt`, etc.

https://docs.qgis.org/2.8/en/docs/user_manual/working_with_raster/raster_calculator.html

I perhaps a new endpoint such as:

```/calc/{keys}/{expression}/{tile_z}/{tile_x}/{tile_y}.png```

Or perhaps even:


Where expression is a URL-encoded string representation of the expression (referencing keys)

**Comment by j08lue** [comment]
Thanks for pursuing this, @pierotofy. I think band math support would be a great addition. A few design questions:

1. Should `/calc` (or what we call it) always result in a single band or can you construct RGB (perhaps with 3 expressions)? -- I'd say RGB should be possible
2. Should an expression be a `&parameter` or a [`/<variable_section>`](http://flask.pocoo.org/docs/1.0/quickstart/#variable-rules) -- I would vote for the former for RGB support
3. FWIW: Sentinel Hub [uses full JS expressions](https://medium.com/sentinel-hub/ad-hoc-testing-of-algorithms-globally-8fb1f564f0f5) for arbitrarily complex band math. I don't think we should go there, though, should we?

**Comment by dionhaefner** [comment]
We could support some functions that behave like NumPy ufuncs. The functionality you propose is `np.where`: `where(x > 50, 5, 10)`. I would be fine having `where` as a special function in the expressions, and it would be easy to implement since it's already in NumPy.

**Comment by pierotofy** [comment]
That would work too. :+1:

**Comment by dionhaefner** [comment]
- RGB: maybe, let's see how singleband expressions turn out first
- `v1`, `v2`: I proposed this to prevent code injection and to prevent naming clashes (what happens if `max` is a key value?)

**Comment by dionhaefner** [comment]
That was fun, so I went ahead and implemented it. The functionality is done, but it needs more testing and documentation. Would be cool if someone could test it a little!

**Comment by mrpgraae** [comment]
Cool, I guess this i a generalization of what we had in mind for #126. I was imagining something more simple, like choose from some pre-defined functions like log10, exp, square and so on, but this is of course much more powerful and I think the API is clean, at least for the singleband case.

I am worried about code injection. Allowing the user to execute arbitrary (not quite I know) code server-side sounds scary. I see you did put a lot of thought into this @dionhaefner, by leaving the user-defined band names out of the expression and by only allowing certain expressions from the Python grammar, but we should be really careful when implementing / changing this, I think.

**Comment by dionhaefner** [comment]
I am confident this is safe; I literally only whitelisted the supported operations and nothing else. But it does feel a bit scary, so if you'd like to reimplement that piece in pyparsing I would be ok with that.

**Comment by dionhaefner** [comment]
A somewhat hacky alternative could be to evaluate through numexpr if it's not too heavyweight.

**Comment by mrpgraae** [comment]
>I am confident this is safe; I literally only whitelisted the supported operations and nothing else. But it does feel a bit scary, so if you'd like to reimplement that piece in pyparsing I would be ok with that.

Looking at the code I also think that it's safe as it is. It's just that things like this are notoriously hard to get right, future changes in API's could for example suddenly make it unsafe. I guess pyparsing would make it safer, by allowing us to be more explicit about what kind of expression we will allow?

Also another thing. I guess this is a pretty efficient vector for DoS attacks. Like if someone passed `expression=sin(sin(sin(sin(sin(sin(sin(...`. Probably won't be a huge deal for Lambda deployments, but could be bad for self-hosted.

**Comment by dionhaefner** [comment]
I planned to add a timeout for the expression to prevent DOS attacks.

Using pyparsing would mean we write our own parser instead of relying on `eval`, so that would be as safe as it gets (same goes for `numexpr`).

**Comment by mrpgraae** [comment]
>I planned to add a timeout for the expression to prevent DOS attacks.

Great!

>Using pyparsing would mean we write our own parser instead of relying on eval, so that would be as safe as it gets (same goes for numexpr).

Cool. I think that would be a good idea to use then. I see quite a lot of complaints about pyparsing being slow, but I guess that probably depends a lot on what is being parsed. I'll do some experiments when I get the chance, to see how it compares to eval and numexpr and if it's not too bad I'll implement this with pyparsing, otherwise I'll take a look at numexpr.

For now, I think it's okay to merge this, maybe wait until the DOS prevention is there 😄

**Comment by dionhaefner** [comment]
Relevant example from `pyparsing`:

https://github.com/pyparsing/pyparsing/blob/master/examples/fourFn.py

Needs some work to adapt to multi-argument functions though. I wouldn't worry about speed, we are just parsing one line anyway.

**Comment by j08lue** [comment]
Since we are evaluating numerical expressions, maybe `numexpr` is the right choice, even though it adds a dependency. Seems like a `pyparsing` solution would require like 300 lines - numexpr probably 2...

**Comment by mrpgraae** [comment]
>Since we are evaluating numerical expressions, maybe numexpr is the right choice, even though it adds a dependency. Seems like a pyparsing solution would require like 300 lines - numexpr probably 2...

pyparsing also adds a depenency and @dionhaefner's pyparsing example is less than 100 lines.
But yes numexpr looks like the simpler choice. Curious as to why you consider it hacky @dionhaefner?

**Comment by vlro** [comment]
Assuming the data is structured the same way as in your example, @dionhaefner:

```
Keys:
satellite
date
bands
```

As it stands, `/compute/` can only use the last key as a parameter, meaning that in this case calculations can only be done on bands from the same acquisition date. This works well for computing indices, but at times we want to do other calculations, e.g. change detection. How can we add this functionality?

Would it be possible to do something like
`localhost:5000/compute/preview.png?expression=v1-v2&v1=S2/20181001/B04&v2=S2/20171001/B4&stretch_range=[0,20000]`

**Comment by dionhaefner** [comment]
@mrpgraae `numexpr` feels hacky because it is a high-performance tool, that just so happens to allow safe execution of NumPy-like array expression strings. It also feels heavyweight, and we do have size constraints for Lambda. But if it works and is not too big I'd prefer it over `pyparsing`.

@j08blue I don't think asteval is any safer than what I wrote.

@vlro Part of the point of TC is that you do the sophisticated processing offline and then just serve it up as-is. This PR is already compromising that somewhat, so I'm hesitant to take this even further. But we can take a vote on it and I'll accept the outcome.

**Comment by vlro** [comment]
At the moment, even without the `compute` implementation we can achieve the same display functionality as the other alternatives, i.e. display pre-computed bands or indices through `singleband` and compute custom band combinations for RGB/False colour/etc with `rgb`. While I agree, @dionhaefner that the `compute` functionality might take away from the simplicity of terracotta (process offline and just serve images), I think it has a few benefits, especially when it comes to differentiating TC from other alternatives that are out there. With the `compute` functionality users would be able to compute custom indices (more complex ones than standard NDVI) on the fly as they need them, rather than having to precompute them. 

I think allowing to pass keys in the expression e.g. `localhost:5000/compute/preview.png?expression=v1-v2&v1=[S2,20181001,B04]&v2=[S2,20171001,B04]&stretch_range=[0,20000]` allows for even more functionality (calculate indices, change detection) and assumes less about the way data is stored than the current proposal which requires the last key to be a parameter. As @dionhaefner  you also mentioned, this would also make `singleband` just a special case of `compute` with `expression=[keys]`. 

Would adding an `expression=(stack([keys],[keys],[keys])` expression to make `rgb` a special case of `compute` be feasible...?

**Comment by dionhaefner** [comment]
As a matter of fact, `asteval` was a lot more secure than what I did, so I implemented something similar. Instead of using `eval` we now walk the AST and execute it recursively, explicitly whitelisting names and operators. That should be as safe as it gets, without new dependencies.

I understand why arbitrary keys are useful, but I think it compromises the API (some endpoints expect keys in the path, some in path and arguments, and some only in arguments?). But as I said, I'd be fine with it if there's a majority for it. Same goes for RGB support I guess.

**Comment by mrpgraae** [comment]
>numexpr feels hacky because it is a high-performance tool, that just so happens to allow safe execution of NumPy-like array expression strings. It also feels heavyweight, and we do have size constraints for Lambda. But if it works and is not too big I'd prefer it over pyparsing.

Okay, I actually thought `numexpr` was just a handy tool for converting string expressions into Numpy operations, didn't know it was that complex. From their own docs:
>NumExpr parses expressions into its own op-codes that are then used by an integrated computing virtual machine. The array operands are split into small chunks that easily fit in the cache of the CPU and passed to the virtual machine.

Sounds like overkill for our use-case.

@vlro TC's main edge over existing alternatives _is_ it's simplicity. It's meant to be a tool for serving and visualizing data. Adding features that do all kinds of cool, but complicated, things takes away from the simplicity and thus the main strength of Terracotta. This is especially true for features that complicate the API. Like @dionhaefner I also think this PR is already bordering on feature creep, but I can see how things like `expression=log10(v1)` are necessary for proper visualization of certain data.

Another thing is, I'm not sure how useful these features _really_ are, even though they seem useful. For every Terracotta deployment, there is one or more web apps that the users can use to interface with Terracotta. If you want to start showing users some new index, like NDVI, you are going to have to add a button or change your web app in some way. If you are going through the trouble of doing that, I don't see why you wouldn't just want to compute NDVI offline, once and for all, rather than having TC compute it over and over again, on every future request.

The only exceptions I can see to the above are for things like change detection, like you say, where you might want to compare 2 arbitrary rasters, or if you wanted to make some playground-like app, where users could type in arbitrary expressions and see the results. While that would be pretty cool, I'm not sure that it justifies the complication of the API.

Maybe there is a case here for a completely new service that does on-the-fly computation on rasters. It could be made to integrate well with TC.

**Comment by mrpgraae** [comment]
>As a matter of fact, asteval was a lot more secure than what I did, so I implemented something similar. Instead of using eval we now walk the AST and execute it recursively, explicitly whitelisting names and operators. That should be as safe as it gets, without new dependencies.

Cool. What I didn't like about the other solution, was that it relied on passing sanitized user input to `eval`. Even if it was probably safe, I've seen so many hacks that break this kind of thing, by somehow bypassing the sanitation. This new method seems a lot safer.

**Comment by dionhaefner** [comment]
Actually I had an idea a while ago to introduce optional plugins to Terracotta. Things like the fancy on-the-fly computations or even timeseries queries could be contained in separate modules, so power users are free to use these features, while new users aren't as overwhelmed.

**Comment by mrpgraae** [comment]
> 
> 
> Actually I had an idea a while ago to introduce optional plugins to Terracotta. Things like the fancy on-the-fly computations or even timeseries queries could be contained in separate modules, so power users are free to use these features, while new users aren't as overwhelmed.

Could be good, if we can make a nice enough plugin interface. Are you thinking in the style of pytest? So there could be a `terracotta-compute` package and a `terracotta-stats` package for example, each possibly having their own section in the config and maybe CLI options.

**Comment by dionhaefner** [comment]
Yes. We could use the same handler as pytest, [pluggy](https://github.com/pytest-dev/pluggy).

**Comment by dionhaefner** [comment]
Merged for now.
