### ISSUE TITLE
best base zoom level where no oversampling has to be done

### ISSUE THREAD

**Issue by chapmanjacobd** [DHI-GRAS/terracotta#247]
I came across this function recently and thought it might be nice metadata to have within Terracotta.

```py
def get_best_zoom_level(input_file, tile_pyramid_type):
    """
    Determine the best base zoom level for a raster.
    "Best" means the maximum zoom level where no oversampling has to be done.
    Parameters
    ----------
    input_file : path to raster file
    tile_pyramid_type : ``TilePyramid`` projection (``geodetic`` or``mercator``)
    Returns
    -------
    zoom : integer
    """
```

https://github.com/ungarj/mapchete/blob/b1194fdec7f116466feafb7afd26e1de3ef7f042/mapchete/io/_misc.py#L30

The use case would be having a little button in the UI which would change the zoom level to the max zoom without oversampling. 

For a compute route one would need to query the `/metadata` route of each source layer and then do something like `Math.min(...listOfMetadata.map(x=>x.baseZoom))`

I'm thinking it could be calculated in the ingest process and served in the `/metadata` route. If it makes sense to add there I'll put a PR together over the next couple weeks

**Comment by dionhaefner** [comment]
I'm not sure how useful this is, since that zoom level typically doesn't exist (unless the raster is perfectly aligned with the Mercator grid). I think this is what is encoded in the second parameter of this function (`tile_pyramid_type`).

But if you are missing this functionality it's fairly easy to attach to your deployments:

```python
driver = tc.get_driver(...)

for raster in raster_files:
    native_zoom_level = get_best_zoom_level(raster, ...)
    mtd = driver.compute_metadata(raster, extra_metadata={"native_zoom_level": native_zoom_level})
    driver.ingest(raster, metadata=mtd)
```

Then, `/metadata` will include your `native_zoom_level` field.
