### ISSUE TITLE
terracotta connect: option to specify listening interface

### ISSUE THREAD

**Issue by gillesserco** [DHI-GRAS/terracotta#268]
Hello

I found the option '--allow-all-ips' for  terracotta serve -d db.sqlite

Is there an identical option for terracotta connect, or a way to specify the interface? didn't' found it. 
If no option is present, where in the code can I force listening to one interfaces or all of them (0.0.0.0)?

Thanks, best regards

Gilles

**Comment by dionhaefner** [comment]
There is no such option by design, since we view the connect interface as a developer tool and not as something that should be facing the outside world.

If you are sure you want to do this, you could change this line:

https://github.com/DHI-GRAS/terracotta/blob/5cbe5412a7caf566a1bee0fcddad7d1d9e3ab8ca/terracotta/scripts/connect.py#L92

Just pass `host="0.0.0.0"` or the desired interface.

**Comment by gillesserco** [comment]
Perfect, thanks very much

I agree with you, but using 0.0.0.0  is convenient for me especially during development time, where the available interfaces of the dev host may be modified, or when the access routes changes...

**Comment by dionhaefner** [comment]
Sounds like this is resolved, then :)
