### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kiksekage** [DHI-GRAS/terracotta#284]
I wanted to use the lovely postgresql driver implemented by @nickeopti sometime back in March when it struck me that these changes werent included in the newest pypi release. Would the changes since 0.7.5 warrant a new release? 🙏

**Comment by j08lue** [comment]
Definitely! I'd say 0.8.0, actually, since we changed the internal API and introduced a new dependency (SQLAlchemy).

IMO 1.0.0 is also overdue, but let us discuss that separately. 😄 

I wrote up the changelog - pls review @dionhaefner and @mrpgraae and feel free to push tha button if you approve.

## What's Changed
* Added support for PostgreSQL databases via refactor to SQLAlchemy by @mrpgraae, @nickeopti, and @chapmanjacobd https://github.com/DHI-GRAS/terracotta/pull/257, https://github.com/DHI-GRAS/terracotta/pull/258, https://github.com/DHI-GRAS/terracotta/pull/260, https://github.com/DHI-GRAS/terracotta/pull/263
* Dropped Python 3.6 support by @dionhaefner https://github.com/DHI-GRAS/terracotta/pull/264
* Improved MySQL connection stability by @panakouris https://github.com/DHI-GRAS/terracotta/pull/267
* Added example script by @tomalrussell https://github.com/DHI-GRAS/terracotta/pull/277
* Fixed APIdoc URL by @dionhaefner https://github.com/DHI-GRAS/terracotta/pull/278
* Fixed process pool by @dionhaefner https://github.com/DHI-GRAS/terracotta/pull/282

**Full Changelog**: https://github.com/DHI-GRAS/terracotta/compare/v0.7.5...main

**Comment by dionhaefner** [comment]
My personal opinion is that we should not release before having #245 sorted out. I have a half-finished implementation but no time to wrap it up. So how about any of the commercial users put some work into it? 🙃

**Comment by mrpgraae** [comment]
> My personal opinion is that we should not release before having #245 sorted out. I have a half-finished implementation but no time to wrap it up. So how about any of the commercial users put some work into it? 🙃 

@dionhaefner I can do that. I have been using [Yoyo Migrations](https://ollycope.com/software/yoyo/latest/) for work recently and I really like it. It's very light-weight and supports all the databases that Terracotta supports. Would you take a look and see if you think we could use it?

**Comment by j08lue** [comment]
> I am uneasy with making _any_ release that breaks current deployments without an easy way to fix it.

Right, I guess none of our past releases changed the database model - but the deployments would still break when you updated, because the version comparison would throw an error. Anyways - awesome if you can move this forward, @mrpgraae!

**Comment by dionhaefner** [comment]
I expanded my simple migration script to finally unblock this. Still happy for contributions that switch that out for something more sophisticated.
