### ISSUE TITLE
Support feature timeseries extraction

### ISSUE THREAD

**Issue by dionhaefner** [DHI-GRAS/terracotta#79]
This is a feature request on behalf of @mads-gras.

The idea is to extract values from a stack of images at the same position. Challenges:

- Opening many COGs over S3 and extracting small subsets will be *slow*.
- We would need another API endpoint, and a clean way to specify the images you want (can't rely on last key as in `/rgb`).
- Terracotta does not know about *pixels*, only about `xyz` tiles and physical bounds. 

If we want to implement this, I think the only way to do it would be to accept a GeoJSON AOI and use that as a window (which can be arbitrarily small). We will also have to do a performance test to see if it's anywhere near acceptable.

**Comment by ewsterrenburg** [comment]
Along the same lines, I'd be interested in elevation profiles (supply which raster should be used, geojson line and a sample interval). Would it be possible to make some kind of plugin architecture?

**Comment by j08lue** [comment]
> Would it be possible to make some kind of plugin architecture?

It might be easier for you to just make a separate function, not a plugin, that handles single-raster point extraction, since there is no information or functionality you really need from Terracotta or its database for this.

We could consider making an endpoint that returns the S3 object key or file path for a given set of keys. That would enable you to use Terracotta to keep track of your rasters and then pass that URI (e.g. `s3://path/to/my/file.tif`) to another (Lambda) function that does the extraction.

So, in short, I don't see enough benefit for single-raster point-along-line extraction to warrant making a fancy plugin system but would rather recommend a micro-service architecture where a different function handles that task - maybe supported by a URI extraction from Terracotta. What do you think?

The case for time series extraction is a bit different, because you need more information from the Terracotta database (the time stamps). However, also here we could consider an API that returns a mapping of time stamp to URI (or URIs for all sub-keys) that you can pass to another function for processing.

**Comment by ewsterrenburg** [comment]
@j08lue
Thanks for the quick reaction.

It makes sense and is more along the lines of what I was originally thinking (then came across terracotta looking for a solution to serve tiles for the layers to be plotted in the chart and started thinking out loud while being blinded by all goodies (api documentation, zappa etc) already in place :)

I can imagine a set of object keys or file paths for a certain location (possibly in combination with key) would be helpful. Let me think this a bit more through...
